apultra -c level-a.bin level-a.apl
apultra -c level-b.bin level-b.apl
apultra -c level-c.bin level-c.apl
apultra -c level-d.bin level-d.apl
apultra -c level-e.bin level-e.apl
apultra -c level-f.bin level-f.apl
apultra -c level-g.bin level-g.apl
apultra -c level-h.bin level-h.apl
apultra -c level-i.bin level-i.apl
apultra -c level-j.bin level-j.apl
apultra -c 32/intro_text.bin intro_text.apl
apultra -c 32/scr_custom_keys.bin scr_custom_keys.apl
apultra -c 32/scr_endgame.bin scr_endgame.apl
apultra -c 32/scr_text.bin scr_text.apl
apultra -c music_1.mco music_title.apl
apultra -c music_3.mco music_lose.apl
apultra -c music_8.mco music_win.apl
apultra -c intro_attr.bin intro_attr.apl
apultra -c hud_attr.bin hud_attr.apl